version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27017:27017"
